name: Cluster creation

on:
  workflow_dispatch:
    inputs:
      CLUSTER_NAME:
        description: 'Name of the cluster'
        required: true
        type: string
      PROJECT_ID: 
        description: 'project-id to use'
        required: true
        type: choice
        options:
          - managed-inventory
          - project2
          - project3
      REGION: 
        description: 'region to use when creating cluster'
        required: true
        type: choice
        options:
          - us-central1
          - us-east1
          - us-east2
      ZONE: 
        description: 'Zone to use when creating cluster'
        required: true
        type: choice
        options:
          - us-central1-c
          - us-central1-a
          - us-east1-a
          - us-east2-d
      ENV:
        description: 'env to use'
        required: true
        type: choice
        options:
          - Dev
          - Stg
          - Qa
          - Prd
jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}
      - name: Create GKE cluster
        run: |
               ./create-cluster.sh --cluster-name=${{ github.event.inputs.CLUSTER_NAME }} --project-id=${{ github.event.inputs.PROJECT_ID }} \
               --zone=${{ github.event.inputs.ZONE }} \
               --region=${{ github.event.inputs.REGION }} \
               --env=${{ github.evnt.inputs.ENV }}


  